### ISSUE TITLE
more shadow and/or round edges for the tiles

### ISSUE THREAD

**Issue by STON3S** [phil65/skin.estuary#146]
The next gen Estuary looks great!
I have only small suggestions to improve the look.

![v17-estuary_ng_000](https://cloud.githubusercontent.com/assets/12751497/20790257/e9ec1008-b7b7-11e6-9961-ec31fb8982a2.jpg)

I think it would looks a bit better if the shadow for all tiles would a bit more/stronger.
I mean the tiles for all covers and the other things in the front.
Currently, the the shadow is hardly noticeable and a bit more of 3D animation  would not harm :)

**Comment by da-anda** [comment]
you can use the "curial" theme of Estuary to get more shadows

**Comment by StoneOffStones** [comment]
Can you tell me more, can't find this option...

**Comment by da-anda** [comment]
didn't I outline the navigation path to follow in order to get there? Click the "gear" in the upper menu of the home screen, then go to "Interface" and there select the "Skin" section in the left menu. On the right you then see the options Kodi is providing to adjust the interface (like selecting a different skin, ...). In the list of these options there is also a "Theme" setting, click it and pick "curial". Below "Theme" there is "Color", click that one to pick a different primary color like green, orange, gold, brown, pink ...

**Comment by STON3S** [comment]
Now I found it...
The reason because i can't saw it was the version of estuary in the beta6.
I installed the newest version from GitHub and than i can choose the Theme-Option.
In Beta6 the option was grey and I can't set it to curial.
Thanks much for this!

The another question was about round edges for the tales, is this for the developers of estuary an interesting improvement?!
Maybe you can say something about it...

**Comment by phil65** [comment]
"No" to rounded edges.
